/* eslint-disable quote-props,dot-notation */

import { getBankCountryList } from '@nimiq/oasis-bank-list';

const CC = {
    'Andorra': 'AD',
    'United Arab Emirates': 'AE',
    'Afghanistan': 'AF',
    'Antigua and Barbuda': 'AG',
    'Anguilla': 'AI',
    'Albania': 'AL',
    'Armenia': 'AM',
    'Angola': 'AO',
    'Antarctica': 'AQ',
    'Argentina': 'AR',
    'American Samoa': 'AS',
    'Austria': 'AT',
    'Australia': 'AU',
    'Aruba': 'AW',
    'Åland Islands': 'AX',
    'Azerbaijan': 'AZ',
    'Bosnia and Herzegovina': 'BA',
    'Barbados': 'BB',
    'Bangladesh': 'BD',
    'Belgium': 'BE',
    'Burkina Faso': 'BF',
    'Bulgaria': 'BG',
    'Bahrain': 'BH',
    'Burundi': 'BI',
    'Benin': 'BJ',
    'Saint Barthélemy': 'BL',
    'Bermuda': 'BM',
    'Brunei Darussalam': 'BN',
    'Bolivia': 'BO',
    'Bonaire, Sint Eustatius and Saba': 'BQ',
    'Brazil': 'BR',
    'Bahamas': 'BS',
    'Bhutan': 'BT',
    'Bouvet Island': 'BV',
    'Botswana': 'BW',
    'Belarus': 'BY',
    'Belize': 'BZ',
    'Canada': 'CA',
    'Cocos (Keeling) Islands': 'CC',
    'Democratic Republic of the Congo': 'CD',
    'Central African Republic': 'CF',
    'Congo': 'CG',
    'Switzerland': 'CH',
    'Côte d\'Ivoire': 'CI',
    'Cook Islands': 'CK',
    'Chile': 'CL',
    'Cameroon': 'CM',
    'China': 'CN',
    'Colombia': 'CO',
    'Costa Rica': 'CR',
    'Cuba': 'CU',
    'Cabo Verde': 'CV',
    'Curaçao': 'CW',
    'Christmas Island': 'CX',
    'Cyprus': 'CY',
    'Czechia': 'CZ',
    'Germany': 'DE',
    'Djibouti': 'DJ',
    'Denmark': 'DK',
    'Dominica': 'DM',
    'Dominican Republic': 'DO',
    'Algeria': 'DZ',
    'Ecuador': 'EC',
    'Estonia': 'EE',
    'Egypt': 'EG',
    'Western Sahara': 'EH',
    'Eritrea': 'ER',
    'Spain': 'ES',
    'Ethiopia': 'ET',
    'Finland': 'FI',
    'Fiji': 'FJ',
    'Falkland Islands [Malvinas]': 'FK',
    'Micronesia': 'FM',
    'Faroe Islands': 'FO',
    'France': 'FR',
    'Gabon': 'GA',
    'United Kingdom of Great Britain and Northern Ireland': 'GB',
    'Grenada': 'GD',
    'Georgia': 'GE',
    'French Guiana': 'GF',
    'Guernsey': 'GG',
    'Ghana': 'GH',
    'Gibraltar': 'GI',
    'Greenland': 'GL',
    'Gambia': 'GM',
    'Guinea': 'GN',
    'Guadeloupe': 'GP',
    'Equatorial Guinea': 'GQ',
    'Greece': 'GR',
    'South Georgia and the South Sandwich Islands': 'GS',
    'Guatemala': 'GT',
    'Guam': 'GU',
    'Guinea-Bissau': 'GW',
    'Guyana': 'GY',
    'Hong Kong': 'HK',
    'Heard Island and McDonald Islands': 'HM',
    'Honduras': 'HN',
    'Croatia': 'HR',
    'Haiti': 'HT',
    'Hungary': 'HU',
    'Indonesia': 'ID',
    'Ireland': 'IE',
    'Israel': 'IL',
    'Isle of Man': 'IM',
    'India': 'IN',
    'British Indian Ocean Territory': 'IO',
    'Iraq': 'IQ',
    'Iran': 'IR',
    'Iceland': 'IS',
    'Italy': 'IT',
    'Jersey': 'JE',
    'Jamaica': 'JM',
    'Jordan': 'JO',
    'Japan': 'JP',
    'Kenya': 'KE',
    'Kyrgyzstan': 'KG',
    'Cambodia': 'KH',
    'Kiribati': 'KI',
    'Comoros': 'KM',
    'Saint Kitts and Nevis': 'KN',
    'North Korea': 'KP',
    'South Korea': 'KR',
    'Kuwait': 'KW',
    'Cayman Islands': 'KY',
    'Kazakhstan': 'KZ',
    'Lao People\'s Democratic Republic': 'LA',
    'Lebanon': 'LB',
    'Saint Lucia': 'LC',
    'Liechtenstein': 'LI',
    'Sri Lanka': 'LK',
    'Liberia': 'LR',
    'Lesotho': 'LS',
    'Lithuania': 'LT',
    'Luxembourg': 'LU',
    'Latvia': 'LV',
    'Libya': 'LY',
    'Morocco': 'MA',
    'Monaco': 'MC',
    'Moldova': 'MD',
    'Montenegro': 'ME',
    'Saint Martin (French part)': 'MF',
    'Madagascar': 'MG',
    'Marshall Islands': 'MH',
    'North Macedonia': 'MK',
    'Mali': 'ML',
    'Myanmar': 'MM',
    'Mongolia': 'MN',
    'Macao': 'MO',
    'Northern Mariana Islands': 'MP',
    'Martinique': 'MQ',
    'Mauritania': 'MR',
    'Montserrat': 'MS',
    'Malta': 'MT',
    'Mauritius': 'MU',
    'Maldives': 'MV',
    'Malawi': 'MW',
    'Mexico': 'MX',
    'Malaysia': 'MY',
    'Mozambique': 'MZ',
    'Namibia': 'NA',
    'New Caledonia': 'NC',
    'Niger': 'NE',
    'Norfolk Island': 'NF',
    'Nigeria': 'NG',
    'Nicaragua': 'NI',
    'Netherlands': 'NL',
    'Norway': 'NO',
    'Nepal': 'NP',
    'Nauru': 'NR',
    'Niue': 'NU',
    'New Zealand': 'NZ',
    'Oman': 'OM',
    'Panama': 'PA',
    'Peru': 'PE',
    'French Polynesia': 'PF',
    'Papua New Guinea': 'PG',
    'Philippines': 'PH',
    'Pakistan': 'PK',
    'Poland': 'PL',
    'Saint Pierre and Miquelon': 'PM',
    'Pitcairn': 'PN',
    'Puerto Rico': 'PR',
    'Palestine': 'PS',
    'Portugal': 'PT',
    'Palau': 'PW',
    'Paraguay': 'PY',
    'Qatar': 'QA',
    'Réunion': 'RE',
    'Romania': 'RO',
    'Serbia': 'RS',
    'Russian Federation': 'RU',
    'Rwanda': 'RW',
    'Saudi Arabia': 'SA',
    'Solomon Islands': 'SB',
    'Seychelles': 'SC',
    'Sudan': 'SD',
    'Sweden': 'SE',
    'Singapore': 'SG',
    'Saint Helena, Ascension and Tristan da Cunha': 'SH',
    'Slovenia': 'SI',
    'Svalbard and Jan Mayen': 'SJ',
    'Slovakia': 'SK',
    'Sierra Leone': 'SL',
    'San Marino': 'SM',
    'Senegal': 'SN',
    'Somalia': 'SO',
    'Suriname': 'SR',
    'South Sudan': 'SS',
    'Sao Tome and Principe': 'ST',
    'El Salvador': 'SV',
    'Sint Maarten (Dutch part)': 'SX',
    'Syrian Arab Republic': 'SY',
    'Eswatini': 'SZ',
    'Turks and Caicos Islands': 'TC',
    'Chad': 'TD',
    'French Southern Territories': 'TF',
    'Togo': 'TG',
    'Thailand': 'TH',
    'Tajikistan': 'TJ',
    'Tokelau': 'TK',
    'Timor-Leste': 'TL',
    'Turkmenistan': 'TM',
    'Tunisia': 'TN',
    'Tonga': 'TO',
    'Turkey': 'TR',
    'Trinidad and Tobago': 'TT',
    'Tuvalu': 'TV',
    'Taiwan': 'TW',
    'United Republic of Tanzania': 'TZ',
    'Ukraine': 'UA',
    'Uganda': 'UG',
    'United States Minor Outlying Islands': 'UM',
    'United States of America': 'US',
    'Uruguay': 'UY',
    'Uzbekistan': 'UZ',
    'Holy See': 'VA',
    'St. Vincent & Grenadines': 'VC',
    'Venezuela': 'VE',
    'British Virgin Islands': 'VG',
    'Virgin Islands (U.S.)': 'VI',
    'Vietnam': 'VN',
    'Vanuatu': 'VU',
    'Wallis and Futuna': 'WF',
    'Samoa': 'WS',
    'Kosovo': 'XK',
    'Yemen': 'YE',
    'Mayotte': 'YT',
    'South Africa': 'ZA',
    'Zambia': 'ZM',
    'Zimbabwe': 'ZW',
} as const;

export const ALL_COUNTRY_CODES: string[] = Object.values(CC);

export const SEPA_COUNTRY_CODES = getBankCountryList();

// https://support.moonpay.com/hc/en-gb/articles/360009279877-What-are-your-supported-countries-states-and-territories-
const MOONPAY_UNSUPPORTED_COUNTRY_CODES: string[] = [
    CC['Afghanistan'],
    CC['Albania'],
    CC['Algeria'],
    CC['Angola'],
    CC['Antigua and Barbuda'],
    CC['Argentina'],
    CC['Armenia'],
    CC['Australia'],
    CC['Azerbaijan'],
    CC['Bahamas'],
    CC['Bahrain'],
    CC['Bangladesh'],
    CC['Barbados'],
    CC['Belarus'],
    CC['Belize'],
    CC['Benin'],
    CC['Bhutan'],
    CC['Bolivia'],
    CC['Bosnia and Herzegovina'],
    CC['Botswana'],
    CC['Brazil'],
    CC['Brunei Darussalam'],
    CC['Burkina Faso'],
    CC['Burundi'],
    CC['Cabo Verde'],
    CC['Cambodia'],
    CC['Cameroon'],
    CC['Canada'],
    CC['Cayman Islands'],
    CC['Central African Republic'],
    CC['Chad'],
    CC['Chile'],
    CC['China'],
    CC['Colombia'],
    CC['Comoros'],
    CC['Congo'],
    CC['Costa Rica'],
    CC['Côte d\'Ivoire'],
    CC['Cuba'],
    CC['Democratic Republic of the Congo'],
    CC['Djibouti'],
    CC['Dominica'],
    CC['Dominican Republic'],
    CC['Ecuador'],
    CC['Egypt'],
    CC['El Salvador'],
    CC['Equatorial Guinea'],
    CC['Eritrea'],
    CC['Eswatini'],
    CC['Ethiopia'],
    CC['Fiji'],
    CC['Gabon'],
    CC['Gambia'],
    CC['Georgia'],
    CC['Ghana'],
    CC['Grenada'],
    CC['Guatemala'],
    CC['Guinea'],
    CC['Guinea-Bissau'],
    CC['Guyana'],
    CC['Haiti'],
    CC['Honduras'],
    CC['Hong Kong'],
    CC['Iceland'],
    CC['India'],
    CC['Indonesia'],
    CC['Iran'],
    CC['Iraq'],
    CC['Israel'],
    CC['Italy'],
    CC['Jamaica'],
    CC['Japan'],
    CC['Jordan'],
    CC['Kazakhstan'],
    CC['Kenya'],
    CC['Kiribati'],
    CC['Kosovo'],
    CC['Kuwait'],
    CC['Kyrgyzstan'],
    CC['Lao People\'s Democratic Republic'],
    CC['Lebanon'],
    CC['Lesotho'],
    CC['Libya'],
    CC['Liberia'],
    CC['North Korea'],
    CC['Madagascar'],
    CC['Malawi'],
    CC['Malaysia'],
    CC['Maldives'],
    CC['Mali'],
    CC['Malta'],
    CC['Marshall Islands'],
    CC['Mauritania'],
    CC['Mauritius'],
    CC['Mexico'],
    CC['Micronesia'],
    CC['Moldova'],
    CC['Mongolia'],
    CC['Montenegro'],
    CC['Morocco'],
    CC['Mozambique'],
    CC['Myanmar'],
    CC['Namibia'],
    CC['Nauru'],
    CC['Nepal'],
    CC['New Zealand'],
    CC['Nicaragua'],
    CC['Niger'],
    CC['Nigeria'],
    CC['North Macedonia'],
    CC['Oman'],
    CC['Pakistan'],
    CC['Palau'],
    CC['Palestine'],
    CC['Panama'],
    CC['Papua New Guinea'],
    CC['Paraguay'],
    CC['Peru'],
    CC['Philippines'],
    CC['Qatar'],
    CC['Romania'],
    CC['Russian Federation'],
    CC['Rwanda'],
    CC['Saint Kitts and Nevis'],
    CC['Saint Lucia'],
    CC['Samoa'],
    CC['Sao Tome and Principe'],
    CC['Saudi Arabia'],
    CC['Senegal'],
    CC['Serbia'],
    CC['Seychelles'],
    CC['Sierra Leone'],
    CC['Singapore'],
    CC['Solomon Islands'],
    CC['Somalia'],
    CC['South Africa'],
    CC['South Sudan'],
    CC['Sri Lanka'],
    CC['St. Vincent & Grenadines'],
    CC['Sudan'],
    CC['Suriname'],
    CC['Syrian Arab Republic'],
    CC['Taiwan'],
    CC['Tajikistan'],
    CC['Thailand'],
    CC['Timor-Leste'],
    CC['Togo'],
    CC['Tonga'],
    CC['Trinidad and Tobago'],
    CC['Tunisia'],
    CC['Turkmenistan'],
    CC['Turkey'],
    CC['Tuvalu'],
    CC['Uganda'],
    CC['Ukraine'],
    CC['United Arab Emirates'],
    CC['British Indian Ocean Territory'],
    CC['United Republic of Tanzania'],
    CC['Uruguay'],
    CC['Uzbekistan'],
    // CC['Vanatu'],
    CC['Venezuela'],
    CC['Vietnam'],
    CC['British Virgin Islands'],
    CC['Virgin Islands (U.S.)'],
    CC['Western Sahara'],
    CC['Yemen'],
    CC['Zambia'],
    CC['Zimbabwe'],

    // NIM not available in Moonpay in the US
    // https://support.moonpay.com/hc/en-gb/articles/360009280177-Which-cryptocurrencies-do-you-support-
    CC['United States of America'],
];

export const MOONPAY_COUNTRY_CODES = ALL_COUNTRY_CODES
    .filter((code) => !MOONPAY_UNSUPPORTED_COUNTRY_CODES.includes(code));

// https://support.simplex.com/hc/en-gb/articles/360014137459-What-are-your-supported-countries-states-and-territories-
// Updated from PDF for May sent in group chat
const SIMPLEX_UNSUPPORTED_COUNTRY_CODES: string[] = [
    CC['Afghanistan'],
    CC['Albania'],
    CC['Barbados'],
    CC['Bangladesh'],
    CC['Belarus'],
    CC['Burkina Faso'],
    CC['Cambodia'],
    CC['Cayman Islands'],
    CC['China'],
    CC['Democratic Republic of the Congo'],
    CC['Cuba'],
    CC['North Korea'],
    CC['Gibraltar'],
    CC['Haiti'],
    CC['Iran'],
    CC['Jamaica'],
    CC['Jordan'],
    CC['Kyrgyzstan'],
    CC['Lebanon'],
    CC['Mali'],
    CC['Morocco'],
    CC['Mozambique'],
    CC['Myanmar'],
    CC['Panama'],
    CC['Philippines'],
    CC['Russian Federation'],
    CC['Senegal'],
    CC['Somalia'],
    CC['Sudan'],
    CC['South Sudan'],
    // CC['North Sudan'],
    CC['Syrian Arab Republic'],
    CC['United Republic of Tanzania'],
    CC['Turkey'],
    CC['Uganda'],
    CC['United Arab Emirates'],
    CC['Yemen'],
    CC['Zimbabwe'],
];

export const SIMPLEX_COUNTRY_CODES = ALL_COUNTRY_CODES
    .filter((code) => !SIMPLEX_UNSUPPORTED_COUNTRY_CODES.includes(code));
